// Parser resilience — tests parse_ytdlp_json against malformed and
// edge-case inputs. yt-dlp's JSON is generated by a live web app and its
// shape drifts over time (see FINDINGS §5); the parser must fail cleanly
// on garbage and not overreach on ambiguous shapes.

#include <doctest/doctest.h>

#include "fetch/parse.h"

#include <nlohmann/json.hpp>

#include <string>

using json = nlohmann::json;

namespace {

// Minimal yt-dlp payload — build 100 valid bins programmatically.
json build_heatmap(double duration_sec, double value_fn(int)) {
    json h = json::array();
    double bin_s = duration_sec / 100.0;
    for (int i = 0; i < 100; ++i) {
        h.push_back({
            {"start_time", i * bin_s},
            {"end_time",   (i + 1) * bin_s},
            {"value",      value_fn(i)},
        });
    }
    return h;
}

json base_payload() {
    return {
        {"id", "abc123XXXXX"},
        {"title", "Test"},
        {"channel", "TestCh"},
        {"duration", 1200},
        {"webpage_url", "https://youtu.be/abc123XXXXX"},
    };
}

} // namespace

TEST_CASE("parse: totally bogus input throws") {
    CHECK_THROWS_AS(crux::fetch::parse_ytdlp_json(""),  std::exception);
    CHECK_THROWS_AS(crux::fetch::parse_ytdlp_json("{"), std::exception);
    CHECK_THROWS_AS(crux::fetch::parse_ytdlp_json("null"), std::exception);
    CHECK_THROWS_AS(crux::fetch::parse_ytdlp_json("[]"), std::exception);
}

TEST_CASE("parse: missing required id throws with helpful message") {
    json j = base_payload();
    j.erase("id");
    CHECK_THROWS_WITH_AS(
        crux::fetch::parse_ytdlp_json(j.dump()),
        doctest::Contains("id"),
        std::exception);
}

TEST_CASE("parse: heatmap absent → optional empty (not an error)") {
    // ~11% of high-view videos have no heatmap. This must be a first-class
    // case, not an exception — see FINDINGS insight 7.
    auto r = crux::fetch::parse_ytdlp_json(base_payload().dump());
    CHECK(!r.heatmap.has_value());
    CHECK(r.video.id == "abc123XXXXX");
}

TEST_CASE("parse: heatmap null → optional empty") {
    json j = base_payload();
    j["heatmap"] = nullptr;
    auto r = crux::fetch::parse_ytdlp_json(j.dump());
    CHECK(!r.heatmap.has_value());
}

TEST_CASE("parse: heatmap with wrong bin count throws") {
    json j = base_payload();
    // 50 bins instead of 100 — should fail loudly.
    json arr = json::array();
    for (int i = 0; i < 50; ++i) {
        arr.push_back({{"start_time", 0.0}, {"end_time", 24.0}, {"value", 0.1}});
    }
    j["heatmap"] = arr;
    CHECK_THROWS(crux::fetch::parse_ytdlp_json(j.dump()));
}

TEST_CASE("parse: numeric fields accept both string and number (yt-dlp quirk)") {
    // yt-dlp has emitted "duration" as either a number or a string in
    // different versions. Parser should coerce.
    json j = base_payload();
    j["duration"] = "1201.5";
    auto r = crux::fetch::parse_ytdlp_json(j.dump());
    CHECK(r.video.duration_sec == doctest::Approx(1201.5));
}

TEST_CASE("parse: is_live flag detected two ways") {
    {
        json j = base_payload();
        j["is_live"] = true;
        j["heatmap"] = build_heatmap(300, [](int){ return 0.1; });
        auto r = crux::fetch::parse_ytdlp_json(j.dump());
        CHECK(r.video.is_live);
    }
    {
        json j = base_payload();
        j["live_status"] = "is_upcoming";
        j["heatmap"] = build_heatmap(300, [](int){ return 0.1; });
        auto r = crux::fetch::parse_ytdlp_json(j.dump());
        CHECK(r.video.is_live);
    }
    {
        json j = base_payload();
        j["live_status"] = "was_live";   // finished — not live
        j["heatmap"] = build_heatmap(300, [](int){ return 0.1; });
        auto r = crux::fetch::parse_ytdlp_json(j.dump());
        CHECK(r.video.is_live == false);
    }
}

TEST_CASE("parse: chapters — null, empty, and full") {
    json j = base_payload();

    j["chapters"] = nullptr;
    CHECK(crux::fetch::parse_ytdlp_json(j.dump()).chapters.empty());

    j["chapters"] = json::array();
    CHECK(crux::fetch::parse_ytdlp_json(j.dump()).chapters.empty());

    j["chapters"] = json::array({
        {{"start_time", 0.0},   {"end_time", 120.0}, {"title", "Intro"}},
        {{"start_time", 120.0}, {"end_time", 900.0}, {"title", "Body"}},
    });
    auto r = crux::fetch::parse_ytdlp_json(j.dump());
    REQUIRE(r.chapters.size() == 2);
    CHECK(r.chapters[0].title == "Intro");
    CHECK(r.chapters[1].start_sec == doctest::Approx(120.0));
}

TEST_CASE("parse: heatmap round-trip preserves values") {
    json j = base_payload();
    j["duration"] = 1000;
    j["heatmap"] = build_heatmap(1000, [](int i){ return i / 99.0; });
    auto r = crux::fetch::parse_ytdlp_json(j.dump());
    REQUIRE(r.heatmap.has_value());
    CHECK(r.heatmap->bins[0].value == doctest::Approx(0.0));
    CHECK(r.heatmap->bins[99].value == doctest::Approx(1.0));
    CHECK(r.heatmap->bin_seconds == doctest::Approx(10.0).epsilon(0.01));
}

TEST_CASE("parse: truncated JSON throws") {
    std::string good = json{{"id", "x"}, {"duration", 1}}.dump();
    // Chop off the closing brace
    std::string bad = good.substr(0, good.size() - 1);
    CHECK_THROWS(crux::fetch::parse_ytdlp_json(bad));
}

TEST_CASE("parse: fuzz — random noise never crashes, always cleanly throws or returns") {
    // The point of fuzz here is: nothing crashes, nothing leaks, and every
    // input either throws a std::exception or returns a well-typed
    // FetchResult. We deliberately don't over-specify the return value —
    // that's the parser's contract to define.
    const char* samples[] = {
        "\0\0\0\0",
        "{}",
        R"({"id": 12345, "duration": null})",
        R"({"id": "x", "duration": 1, "heatmap": {}})",
        R"({"id": "x", "duration": 1, "heatmap": [1,2,3]})",
        R"({"id": "x", "duration": 1, "heatmap": ["foo"]})",
        R"({"id": "x", "duration": "abc"})",
        R"({"id": "x", "duration": 1, "chapters": "not-an-array"})",
        R"({"id": ""})",
    };
    for (const char* s : samples) {
        bool ok_or_threw = false;
        try {
            auto r = crux::fetch::parse_ytdlp_json(s);
            // If it did parse, `id` must be a well-formed string (empty is
            // allowed — the parser accepts it because yt-dlp sometimes emits
            // odd shapes; the pipeline stage rejects empties downstream).
            (void)r.video.id;
            ok_or_threw = true;
        } catch (const std::exception&) {
            ok_or_threw = true;   // expected for most of these
        }
        CHECK(ok_or_threw);
    }
}
