"""Generates src/media/english_words.cpp — a frequency-ranked English wordlist
for the transliterator's fuzzy phonetic recovery pass.

Input: tools/_english_words_raw.txt (google-10000-english, MIT).
Output: an anonymous-namespace constexpr array grouped by first letter and
sorted by length, so the fuzzy match at runtime only scans the same-letter
same-length-ish bucket.

Regenerate with:  python tools/gen_english_words.py
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IN = os.path.join(ROOT, "tools", "_english_words_raw.txt")
OUT = os.path.join(ROOT, "src", "media", "english_words.cpp")

# Cap at 3000 to keep the binary small and the search tight.  The list is
# already frequency-sorted so the first N are the most useful.
CAP = 3000

# Words shorter than 4 letters are dropped: they collide with too many Hindi
# particles ("ko", "hai", "aur") and would over-correct.
MIN_LEN = 4
MAX_LEN = 16

# Blacklist: common English words that are ALSO common Hindi words when
# romanized — we must NOT replace the Hindi form with these.
BLACKLIST = {
    "hai", "hain", "koi", "toh", "kya", "kyun", "jab", "tab", "yeh", "wah",
    "meri", "mera", "tera", "teri", "tumhara", "unka", "iska", "uska",
    "din", "raat", "aaj", "kal", "abhi", "yaha", "waha", "kaha", "jaha",
    "sab", "kuch", "kuchh", "nahi", "nahin", "haan", "phir", "bhi", "hi",
    "aur", "par", "lekin", "matlab", "asal", "acha", "achha", "theek",
    # These English words trigger too many false positives:
    "hi", "as", "an", "on", "up", "in", "it", "to", "is", "of", "by", "we",
    "me", "us", "he", "or", "at", "no", "so", "if", "do", "be", "am",
}

words = []
seen = set()
with open(IN, encoding="utf-8") as f:
    for line in f:
        w = line.strip().lower()
        if not re.fullmatch(r"[a-z]+", w): continue
        if w in BLACKLIST: continue
        if len(w) < MIN_LEN or len(w) > MAX_LEN: continue
        if w in seen: continue
        seen.add(w)
        words.append(w)
        if len(words) >= CAP: break

# Group by (first_letter, length_bucket).  Length buckets: [4-5], [6-7],
# [8-9], [10-11], [12+].  This lets the runtime scan only ~50 words per
# lookup instead of 3000.
def bucket(w):
    return (w[0], min(4, (len(w) - MIN_LEN) // 2))

buckets = {}
for w in words:
    buckets.setdefault(bucket(w), []).append(w)

# Also emit a flat rank map (word -> frequency rank) so if two words are
# equidistant we pick the more common one.
rank = {w: i for i, w in enumerate(words)}

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("// GENERATED by tools/gen_english_words.py from tools/_english_words_raw.txt\n")
    f.write("// (google-10000-english, MIT).  Do not edit by hand.\n")
    f.write('#include "media/english_words.h"\n\n')
    f.write("#include <array>\n")
    f.write("#include <string_view>\n\n")
    f.write("namespace crux::media {\n\n")
    f.write(f"// {len(words)} frequency-ranked English words, bucketed by\n")
    f.write("// (first_letter, length_bucket) so fuzzy lookup is fast.\n\n")
    f.write("namespace {\n\n")

    for i, ((letter, lb), ws) in enumerate(sorted(buckets.items())):
        f.write(f"constexpr const char* kB_{letter}_{lb}[] = {{\n    ")
        line = []
        for w in ws:
            line.append(f'"{w}"')
            if sum(len(x) for x in line) > 68:
                f.write(", ".join(line) + ",\n    ")
                line = []
        if line: f.write(", ".join(line) + ",\n")
        f.write("};\n")

    f.write("\nconstexpr Bucket kBuckets[] = {\n")
    for (letter, lb), ws in sorted(buckets.items()):
        f.write(f'    {{\'{letter}\', {lb}, kB_{letter}_{lb}, {len(ws)}}},\n')
    f.write("};\n\n")
    f.write("} // namespace\n\n")
    f.write("std::span<const Bucket> english_word_buckets() {\n"
            "    return {kBuckets, sizeof(kBuckets) / sizeof(kBuckets[0])};\n"
            "}\n\n")
    f.write("} // namespace crux::media\n")

print(f"wrote {OUT}: {len(words)} words in {len(buckets)} buckets")
