// Frequency-ranked English wordlist for the transliterator's fuzzy phonetic
// recovery pass.  Generated by tools/gen_english_words.py.
#pragma once

#include <cstddef>
#include <span>
#include <string>

namespace crux::media {

struct Bucket {
    char first;
    int  len_bucket;  // 0 = len 4-5, 1 = 6-7, 2 = 8-9, 3 = 10-11, 4 = 12+
    const char* const* words;
    std::size_t count;
};

std::span<const Bucket> english_word_buckets();

// Given a lowercase-latin phonetic string, returns the closest English word
// within edit distance 2 (case-sensitive result — lowercase).  Returns empty
// when no acceptable match exists.  Guards: minimum length 4, distance ≤
// max(2, len/4).  Bucketed by first letter and ±1 length-bucket so a lookup
// scans ~150 words at worst.
std::string recover_english(const std::string& phon);

} // namespace crux::media
