// GENERATED by tools/gen_english_words.py from tools/_english_words_raw.txt
// (google-10000-english, MIT).  Do not edit by hand.
#include "media/english_words.h"

#include <array>
#include <string_view>

namespace crux::media {

// 3000 frequency-ranked English words, bucketed by
// (first_letter, length_bucket) so fuzzy lookup is fast.

namespace {

constexpr const char* kB_a_0[] = {
    "about", "also", "after", "area", "again", "april", "above", "audio", "areas", "added", "away",
    "able", "arts", "adult", "auto", "along", "among", "album", "apply", "asked", "allow", "asian",
    "anti", "anal", "award", "agent", "asia", "apple", "agree", "army", "alone", "admin", "avoid",
    "abuse", "aids", "atom", "alert", "anime", "acid", "ahead", "alpha", "adobe", "arms", "aware",
    "angel", "array", "ages", "acts", "allen",
};
constexpr const char* kB_a_1[] = {
    "address", "access", "account", "another", "article", "author", "around", "action", "against",
    "august", "america", "always", "archive", "already", "average", "amount", "annual", "active",
    "africa", "agency", "across", "anyone", "advice", "airport", "artist", "almost", "answer",
    "animal", "amazon", "animals", "artists", "allows", "authors", "ability", "awards", "answers",
    "agents", "angeles", "african", "applied", "advance", "auction", "allowed", "actions",
    "accept", "appear", "actual", "amateur", "apparel", "arizona", "affairs", "avenue", "attack",
    "appears", "adults", "atlanta", "alaska", "austin", "andrew", "assets", "assist", "amounts",
    "academy", "agreed", "aspects", "austria", "appeal", "alabama", "achieve", "adding",
    "amazing", "advisor", "attempt", "alcohol", "affect", "albums", "agenda", "anyway", "ancient",
    "adopted", "alerts", "assume", "adapter",
};
constexpr const char* kB_a_2[] = {
    "available", "american", "advanced", "articles", "analysis", "australia", "agreement",
    "archives", "advertise", "activity", "although", "anything", "addition", "according",
    "actually", "approach", "authority", "abstract", "academic", "approved", "accepted",
    "agencies", "attention", "accounts", "argument", "attorney", "auctions", "affiliate",
    "approval", "adventure", "assistant", "assembly", "advantage", "anonymous", "associate",
    "apartment", "accuracy", "addresses", "announced", "automatic", "amendment", "americans",
    "accurate", "aircraft", "audience", "assigned", "affected", "anderson", "advisory",
    "anywhere", "atlantic", "appendix", "arkansas", "attached", "alliance",
};
constexpr const char* kB_a_3[] = {
    "accessories", "application", "activities", "additional", "association", "advertising",
    "appropriate", "associated", "assessment", "alternative", "assistance", "associates",
    "australian", "automotive", "accounting", "apartments", "acceptance", "affiliates",
    "applicable", "agriculture", "accordance", "annotation", "appliances", "authorities",
    "attractions", "authorized",
};
constexpr const char* kB_a_4[] = {
    "applications", "availability", "administration", "accommodation", "announcements",
    "architecture", "administrative", "approximately", "automatically", "advertisement",
    "administrator", "agricultural",
};
constexpr const char* kB_b_0[] = {
    "been", "back", "best", "books", "book", "based", "black", "being", "both", "board", "below",
    "blog", "body", "blue", "baby", "beach", "bill", "bank", "basic", "brand", "base", "build",
    "bush", "band", "brown", "built", "blood", "basis", "bring", "boys", "born", "break", "block",
    "blogs", "begin", "bible", "ball", "buyer", "began", "birth", "boat", "brain", "brief", "bear",
    "blow", "bytes", "banks", "bath", "beta", "brian", "bags", "bars", "bird", "bids", "bonus",
    "beat", "babes", "bass", "boxes", "bell", "bike", "buddy", "bond", "blues", "bears", "babe",
    "bound", "bowl",
};
constexpr const char* kB_b_1[] = {
    "before", "because", "between", "better", "browse", "become", "beauty", "believe", "british",
    "button", "browser", "budget", "behind", "buying", "boards", "brands", "battery", "boston",
    "benefit", "beyond", "bottom", "basket", "balance", "breast", "brought", "bondage", "became",
    "branch", "bridge", "brother", "binding", "billion", "bought", "broken", "battle", "banking",
    "brazil", "becomes", "bedroom", "bureau", "backup", "blonde", "belgium", "booking", "biology",
    "border", "britain", "begins", "blowjob",
};
constexpr const char* kB_b_2[] = {
    "business", "building", "benefits", "beautiful", "beginning", "breakfast", "baseball",
    "behavior", "birthday", "breaking", "bookmark", "buildings", "batteries", "broadband",
    "bluetooth", "biography", "becoming", "brothers",
};
constexpr const char* kB_b_3[] = {
    "background", "businesses", "basketball",
};
constexpr const char* kB_c_0[] = {
    "click", "city", "could", "code", "check", "case", "care", "call", "class", "card", "cost",
    "come", "cart", "club", "court", "china", "cards", "child", "cell", "color", "cars", "close",
    "costs", "cheap", "cover", "clear", "cases", "chat", "copy", "cash", "cross", "came", "cable",
    "cause", "cnet", "comes", "cool", "core", "civil", "coast", "chief", "clean", "chris", "cells",
    "calls", "canon", "cold", "chair", "crime", "count", "claim", "creek", "cock", "chain", "camp",
    "chart", "clubs", "codes", "cast", "carry", "clips", "clip", "cent", "cycle", "cape", "cisco",
    "clock", "cream", "coach", "cook", "costa", "crazy", "crew",
};
constexpr const char* kB_c_1[] = {
    "contact", "company", "center", "county", "current", "control", "change", "content",
    "country", "compare", "college", "course", "canada", "credit", "comment", "create", "changes",
    "central", "council", "common", "called", "centre", "choose", "camera", "chapter", "church",
    "created", "casino", "certain", "career", "coming", "client", "capital", "culture", "choice",
    "courses", "channel", "custom", "cancer", "cameras", "chicago", "classic", "command",
    "cities", "catalog", "charge", "chinese", "century", "classes", "campus", "careers",
    "complex", "changed", "connect", "correct", "charles", "couple", "chance", "clients",
    "coffee", "closed", "context", "covered", "claims", "charges", "corner", "column", "centers",
    "counter", "covers", "credits", "clearly", "concept", "conduct", "calling", "comics",
    "contain", "crystal", "christ", "comfort", "colors", "cruise", "carried", "clothes",
    "caused", "circuit", "copies", "charts", "census", "compact", "climate", "concern", "cheats",
    "circle", "cooking", "crafts", "cables", "cotton", "causes", "concert", "comedy", "carrier",
    "confirm", "checks",
};
constexpr const char* kB_c_2[] = {
    "copyright", "comments", "community", "computer", "children", "customer", "category",
    "complete", "committee", "companies", "computers", "calendar", "currently", "corporate",
    "customers", "countries", "contents", "continue", "condition", "clothing", "christmas",
    "consumer", "contract", "christian", "carolina", "canadian", "contains", "completed",
    "consider", "character", "capacity", "creative", "columbia", "critical", "colorado",
    "coverage", "clinical", "currency", "commerce", "cultural", "continued", "chemical",
    "component", "congress", "creating", "campaign", "challenge", "certified", "computing",
    "contacts", "compared", "classical", "criminal", "criteria", "changing", "checkout",
    "contained", "controls", "combined", "creation", "chairman", "cleaning", "concerns",
    "connected", "certainly", "concerned", "conflict", "conducted", "citizens", "contracts",
    "chemistry", "continues", "checking", "celebrity", "channels", "chocolate", "constant",
    "concepts", "clearance", "converter", "colleges",
};
constexpr const char* kB_c_3[] = {
    "categories", "conditions", "california", "collection", "conference", "commercial",
    "commission", "corporation", "connection", "considered", "components", "certificate",
    "communities", "classifieds", "competition", "characters", "compliance", "comparison",
    "completely", "compatible", "consulting", "constitutes", "containing", "combination",
    "convention", "conversion", "continuing", "competitive", "connecticut", "collections",
    "concerning", "curriculum", "controlled", "commitment", "classified", "confidence",
    "consistent", "connections", "contribute", "challenges",
};
constexpr const char* kB_c_4[] = {
    "construction", "communications", "communication", "configuration", "comprehensive",
    "collectibles", "certification", "contemporary", "conservation", "certificates",
    "compensation", "characteristics", "circumstances",
};
constexpr const char* kB_d_0[] = {
    "date", "data", "does", "days", "down", "david", "drive", "daily", "done", "deals", "death",
    "doing", "drug", "deal", "door", "deep", "debt", "dance", "dark", "dead", "diet", "dvds", "drugs",
    "dates", "drop", "died", "draft", "disc", "dream", "disk", "desk", "dave", "diego", "duty",
    "depth", "davis", "dual", "drink", "dell", "dogs", "devel", "delta", "dress", "diff", "dick",
    "dean", "draw",
};
constexpr const char* kB_d_1[] = {
    "details", "design", "during", "digital", "display", "direct", "domain", "double", "degree",
    "disease", "develop", "dating", "default", "defined", "device", "desktop", "driver",
    "devices", "detail", "demand", "discuss", "dollars", "driving", "doctor", "diamond",
    "defense", "define", "damage", "dollar", "delete", "decided", "designs", "dining", "dakota",
    "dallas", "drivers", "daniel", "dynamic", "despite", "degrees", "disney", "drives", "dealer",
    "dinner", "dealers", "denver", "dental", "debate", "deliver",
};
constexpr const char* kB_d_2[] = {
    "download", "directory", "december", "different", "delivery", "director", "database",
    "district", "downloads", "document", "designed", "discount", "decision", "division",
    "documents", "developed", "distance", "directly", "detailed", "described", "determine",
    "difficult", "developer", "domestic", "dedicated", "direction", "decisions", "designer",
    "displayed", "delivered", "directors", "daughter", "discover", "discussed", "describe",
    "directed", "diseases", "disabled", "discovery",
};
constexpr const char* kB_d_3[] = {
    "development", "department", "description", "discussion", "disclaimer", "definition",
    "difference", "directions", "developing", "dictionary", "designated", "determined",
    "discussions", "destination", "departments", "distributed", "differences", "developers",
    "democratic", "dimensions",
};
constexpr const char* kB_d_4[] = {
    "distribution", "documentation",
};
constexpr const char* kB_e_0[] = {
    "email", "each", "ebay", "even", "every", "east", "easy", "event", "enter", "ever", "early",
    "else", "edit", "error", "entry", "earth", "extra", "enjoy", "eyes", "edge", "equal", "ends",
    "ended", "eight", "eric", "empty", "evil", "euro", "exist", "exit", "exact",
};
constexpr const char* kB_e_1[] = {
    "events", "english", "estate", "example", "energy", "edition", "either", "europe", "enough",
    "effects", "engine", "effect", "england", "editor", "express", "ensure", "entire", "except",
    "economy", "ending", "easily", "effort", "enable", "eastern", "entries", "errors", "efforts",
    "expert", "element", "expect", "earlier", "evening", "enlarge", "experts", "exactly",
    "explore", "equity", "extreme", "easier", "engines", "explain", "extent", "export", "expand",
    "edward", "entered", "edited", "enabled", "enhance", "editors",
};
constexpr const char* kB_e_2[] = {
    "education", "equipment", "economic", "european", "exchange", "effective", "executive",
    "everyone", "evidence", "excellent", "existing", "employees", "expected", "external",
    "electric", "employee", "elements", "emergency", "exercise", "essential", "examples",
    "election", "extended", "extension", "estimated", "eligible", "editorial", "economics",
    "estimates", "exclusive", "exposure", "evolution", "elizabeth", "establish", "expressed",
    "employer", "expenses", "extremely", "ericsson", "explorer", "efficient", "engineer",
    };
constexpr const char* kB_e_3[] = {
    "experience", "electronics", "environment", "everything", "engineering", "employment",
    "electronic", "especially", "enterprise", "educational", "established", "evaluation",
    "electrical", "expression", "enterprises", "experienced", "experiences", "equivalent",
    "elementary", "enforcement", "efficiency",
};
constexpr const char* kB_e_4[] = {
    "entertainment", "environmental", "encyclopedia",
};
constexpr const char* kB_f_0[] = {
    "from", "free", "first", "find", "full", "forum", "file", "found", "form", "food", "field",
    "four", "files", "film", "five", "front", "final", "fast", "fact", "feel", "fire", "face",
    "force", "fine", "flash", "fund", "focus", "fall", "forms", "feed", "feet", "funds", "fees",
    "floor", "fish", "fair", "fixed", "fully", "farm", "flat", "flow", "frame", "firm", "ford",
    "foot", "fuel", "fuck", "fresh", "facts", "faith", "films", "fill", "fort", "funny", "false",
    "felt", "falls", "flag", "feeds", "frank", "fight", "filed", "font", "fail", "fans", "fear",
    "faqs", "firms", "fruit",
};
constexpr const char* kB_f_1[] = {
    "family", "forums", "friend", "future", "format", "friends", "further", "france", "federal",
    "finance", "florida", "friday", "figure", "french", "follow", "foreign", "female", "feature",
    "forward", "flowers", "fitness", "filter", "faculty", "finally", "father", "fucking",
    "funding", "fiction", "former", "fashion", "forest", "factors", "fishing", "fields",
    "fantasy", "flight", "freedom", "factor", "finding", "failure", "follows", "forces",
    "flower", "flights", "forgot", "faster", "forced", "failed", "figures", "finish", "famous",
    "frames", "factory", "feeling", "fourth", "forget", "fiscal", "filled", "formal",
};
constexpr const char* kB_f_2[] = {
    "following", "features", "feedback", "financial", "february", "function", "furniture",
    "featured", "friendly", "favorite", "football", "functions", "families", "francisco",
    "facility", "framework", "festival", "followed", "favorites", "frequency", "forecast",
    "finished", "financing",
};
constexpr const char* kB_f_3[] = {
    "facilities", "foundation", "functional", "frequently",
};
constexpr const char* kB_g_0[] = {
    "good", "group", "games", "great", "game", "guide", "going", "give", "girls", "gift", "given",
    "green", "gold", "gifts", "girl", "golf", "glass", "grand", "guest", "grade", "goods", "gets",
    "grant", "goes", "gives", "gear", "goal", "guys", "goals", "gave", "gamma", "gone", "gene",
    "gain", "guess", "grow", "greek", "genre",
};
constexpr const char* kB_g_1[] = {
    "general", "gallery", "groups", "garden", "getting", "global", "germany", "google", "growth",
    "george", "ground", "guides", "greater", "german", "georgia", "giving", "growing", "guitar",
    "golden", "graphic", "gaming", "gratis", "gender", "generic", "guests", "grants",
};
constexpr const char* kB_g_2[] = {
    "graphics", "galleries", "graduate", "generally", "guarantee", "generated", "gambling",
    "greatest", "guidance", "glossary",
};
constexpr const char* kB_g_3[] = {
    "government", "guidelines", "generation", "guaranteed",
};
constexpr const char* kB_h_0[] = {
    "have", "home", "here", "help", "high", "hotel", "house", "hours", "human", "hard", "hand",
    "head", "heart", "half", "html", "held", "hope", "hour", "huge", "homes", "hill", "hold", "happy",
    "hall", "hair", "horse", "host", "hands", "hear", "hits", "heard", "heat", "heavy", "hire",
    "harry", "hello", "hong", "helps", "henry", "hide", "hole", "hills", "holy", "hell",
};
constexpr const char* kB_h_1[] = {
    "health", "hotels", "history", "however", "having", "hosting", "holiday", "higher", "housing",
    "highest", "helpful", "highly", "himself", "hearing", "houston", "hentai", "hawaii",
    "handle", "height", "healthy", "houses", "hunter", "happen", "hidden", "holding", "helping",
    "hosted", "highway", "husband", "howard", "hockey",
};
constexpr const char* kB_h_2[] = {
    "hardware", "homepage", "hospital", "holidays", "hardcore", "headlines", "handling",
    "household", "happened", "heritage", "hardcover", "hampshire", "historic",
};
constexpr const char* kB_h_3[] = {
    "historical", "healthcare",
};
constexpr const char* kB_i_0[] = {
    "into", "info", "items", "item", "index", "image", "issue", "india", "ideas", "idea", "italy",
    "input", "iraq", "isbn", "ipod", "inch", "icon", "iron", "iowa", "intel", "ideal", "irish",
    "iran",
};
constexpr const char* kB_i_1[] = {
    "include", "issues", "images", "island", "income", "inside", "islands", "improve", "impact",
    "ireland", "instead", "indian", "incest", "itself", "initial", "install", "israel", "italian",
    "indiana", "issued", "injury", "import", "instant", "inches", "indeed",
};
constexpr const char* kB_i_2[] = {
    "internet", "including", "insurance", "industry", "important", "interest", "includes",
    "included", "increase", "institute", "involved", "interface", "internal", "increased",
    "illinois", "interests", "informed", "intended", "identify", "interview", "installed",
    "improved", "interior", "identity", "influence", "instance", "immediate", "indicate",
    "investor", "inventory", "indicated",
};
constexpr const char* kB_i_3[] = {
    "information", "individual", "investment", "industrial", "independent", "interested",
    "instruments", "interesting", "individuals", "immediately", "integrated", "improvement",
    "interactive", "identified", "integration", "industries", "introduced", "increasing",
    "importance", "interracial", "instruction", "institution", "interviews",
};
constexpr const char* kB_i_4[] = {
    "international", "introduction", "instructions", "implementation", "installation",
    "institutions", "intelligence", "infrastructure", "investigation", "identification",
    };
constexpr const char* kB_j_0[] = {
    "just", "john", "jobs", "join", "june", "july", "james", "japan", "java", "jack", "jump", "jones",
    "joint", "jesus", "judge", "jazz", "jeff", "jean",
};
constexpr const char* kB_j_1[] = {
    "january", "journal", "jewelry", "joined", "jersey", "justice", "johnson", "jackson",
    "joseph", "junior", "jordan", "jewish",
};
constexpr const char* kB_j_2[] = {
    "japanese",
};
constexpr const char* kB_j_3[] = {
    "javascript",
};
constexpr const char* kB_k_0[] = {
    "know", "keep", "kids", "known", "king", "kind", "kong", "kinds", "knew", "korea", "kelly",
    "kept", "kill", "knows", "kevin", "kits", "keys",
};
constexpr const char* kB_k_1[] = {
    "kingdom", "kitchen", "kansas", "keyword", "keeping", "killed",
};
constexpr const char* kB_k_2[] = {
    "knowledge", "keywords", "kentucky",
};
constexpr const char* kB_l_0[] = {
    "like", "list", "last", "links", "life", "line", "local", "long", "link", "level", "love",
    "learn", "look", "left", "live", "large", "less", "login", "legal", "light", "least", "land",
    "linux", "loan", "lake", "later", "loss", "loans", "lines", "lost", "lower", "leave", "logo",
    "lead", "late", "lists", "lord", "laws", "lots", "looks", "lives", "label", "limit", "louis",
    "load", "labor", "latin", "laser", "lack", "leads", "lady", "layer", "lane", "lose", "logic",
    "lens", "lewis", "legs", "lock",
};
constexpr const char* kB_l_1[] = {
    "listing", "little", "library", "looking", "latest", "london", "listed", "living", "limited",
    "lyrics", "license", "lesbian", "length", "levels", "letter", "located", "larger", "leading",
    "likely", "longer", "largest", "listen", "lowest", "leather", "league", "letters", "leader",
    "leaders", "looked", "logged", "laptop", "lawyer", "ladies", "luxury", "lawyers", "lights",
    "leaving", "launch", "leisure", "learned", "linear", "linked", "lessons", "leaves", "laptops",
    };
constexpr const char* kB_l_2[] = {
    "location", "language", "learning", "listings", "locations", "languages", "lighting",
    "lingerie", "libraries", "liability", "licensed", "louisiana", "lesbians", "lifestyle",
    };
constexpr const char* kB_l_3[] = {
    "literature", "leadership", "laboratory", "legislation",
};
constexpr const char* kB_m_0[] = {
    "more", "most", "music", "make", "many", "mail", "must", "made", "much", "media", "main", "money",
    "model", "movie", "march", "might", "month", "major", "means", "miles", "mark", "meet", "makes",
    "mean", "mind", "menu", "move", "mode", "male", "maps", "metal", "multi", "mary", "match",
    "mini", "maybe", "mike", "milf", "motor", "mass", "miss", "magic", "mount", "moved", "mouse",
    "miami", "minor", "mine", "math", "moon", "maine", "mixed", "matt", "mesh", "mouth", "meter",
    "mysql", "micro", "mile", "mens",
};
constexpr const char* kB_m_1[] = {
    "message", "member", "members", "movies", "market", "medical", "mobile", "memory", "making",
    "meeting", "million", "months", "minutes", "methods", "manager", "models", "michael",
    "method", "monday", "mature", "middle", "machine", "matter", "mexico", "master", "maximum",
    "mother", "modern", "mailing", "morning", "mission", "moving", "medium", "minimum", "martin",
    "manual", "museum", "monthly", "musical", "module", "motion", "monitor", "markets", "minute",
    "myself", "marine", "manage", "missing", "mental", "moment", "measure", "managed", "married",
    "matters", "meaning", "manner", "matrix", "miller", "mostly", "matches", "modules", "montana",
    };
constexpr const char* kB_m_2[] = {
    "messages", "marketing", "microsoft", "material", "magazine", "materials", "mortgage",
    "military", "multiple", "medicine", "mountain", "modified", "michigan", "magazines",
    "minister", "measures", "meetings", "machines", "merchant", "motorola", "minnesota",
    "movement", "matching", "maintain", "maryland", "marriage", "missouri", "ministry",
    "mentioned", "majority", "managing", "managers",
};
constexpr const char* kB_m_3[] = {
    "management", "membership", "maintenance", "monitoring", "multimedia", "maintained",
    "marketplace", "mathematics", "mississippi",
};
constexpr const char* kB_m_4[] = {
    "manufacturer", "manufacturing", "manufacturers", "miscellaneous", "massachusetts",
    };
constexpr const char* kB_n_0[] = {
    "news", "name", "next", "need", "north", "note", "never", "night", "needs", "nude", "none",
    "near", "notes", "names", "nice", "nokia", "naked", "named", "null", "noted", "nine", "noise",
    "node",
};
constexpr const char* kB_n_1[] = {
    "number", "network", "notice", "natural", "nature", "needed", "nothing", "numbers", "normal",
    "nation", "nursing", "native", "nuclear", "nearly", "nations", "nearby", "newest", "nevada",
    "notify", "neither",
};
constexpr const char* kB_n_2[] = {
    "national", "november", "necessary", "networks", "northern", "negative", "nutrition",
    "newspaper", "notebook",
};
constexpr const char* kB_n_3[] = {
    "newsletter", "navigation", "networking", "newsletters", "netherlands",
};
constexpr const char* kB_n_4[] = {
    "neighborhood",
};
constexpr const char* kB_o_0[] = {
    "other", "only", "over", "order", "open", "offer", "once", "often", "owner", "ohio", "older",
    "oral", "ones", "owned", "ocean", "onto", "occur",
};
constexpr const char* kB_o_1[] = {
    "online", "office", "october", "offers", "options", "others", "orders", "overall", "object",
    "outside", "option", "owners", "opinion", "output", "outdoor", "offered", "officer",
    "orange", "oregon", "opening", "ontario", "objects", "origin", "obtain", "offices", "optical",
    "orlando", "organic", "opened", "offline",
};
constexpr const char* kB_o_2[] = {
    "original", "official", "operating", "overview", "operation", "otherwise", "optional",
    "offering", "obtained", "opinions", "officials", "oklahoma", "officers", "ordering",
    "outdoors", "operator", "observed", "objective",
};
constexpr const char* kB_o_3[] = {
    "operations", "opportunity", "originally", "objectives",
};
constexpr const char* kB_o_4[] = {
    "organization", "opportunities", "organizations", "organisation",
};
constexpr const char* kB_p_0[] = {
    "page", "price", "post", "part", "phone", "pages", "photo", "power", "place", "posts", "press",
    "print", "point", "plan", "play", "party", "park", "paper", "poker", "porn", "past", "parts",
    "plus", "paul", "pics", "port", "plans", "prior", "paid", "peter", "pussy", "pass", "prev",
    "panel", "plant", "pool", "pack", "paris", "poor", "peace", "path", "piece", "palm", "pain",
    "pink", "phase", "patch", "pick", "prime", "porno", "proof", "pets", "pair", "parks", "peak",
    "plug", "perl", "plate", "plain", "poll", "pure",
};
constexpr const char* kB_p_1[] = {
    "people", "product", "policy", "please", "public", "privacy", "program", "posted", "prices",
    "project", "profile", "private", "provide", "process", "photos", "person", "payment",
    "problem", "picture", "popular", "powered", "period", "present", "percent", "player",
    "points", "package", "players", "printer", "phones", "primary", "purpose", "police",
    "paypal", "parents", "perfect", "pacific", "protein", "partner", "parties", "places",
    "pretty", "papers", "playing", "parent", "pricing", "patient", "perhaps", "persons",
    "poster", "pocket", "premium", "protect", "prevent", "plants", "plastic", "produce",
    "placed", "played", "profit", "posters", "parking", "pattern", "passed", "promote", "pubmed",
    "perform", "portal", "postal", "physics", "posting", "preview", "proper", "phoenix",
    "printed", "prints", "planet", "permit", "pieces", "poetry", "prince", "portion",
};
constexpr const char* kB_p_2[] = {
    "products", "pictures", "personal", "previous", "property", "provided", "programs",
    "password", "possible", "problems", "president", "provides", "planning", "projects",
    "policies", "position", "published", "purchase", "practice", "political", "potential",
    "physical", "probably", "publisher", "partners", "patients", "providing", "programme",
    "positive", "proposed", "politics", "pressure", "purposes", "progress", "presented",
    "packages", "provider", "professor", "processes", "produced", "paperback", "providers",
    "practices", "platform", "procedure", "printing", "portable", "powerful", "personnel",
    "priority", "payments", "prepared", "protocol", "protected", "proposal", "profiles",
    "performed", "pharmacy", "permanent", "portfolio", "practical", "presence", "principal",
    "positions", "panasonic", "permalink", "provision", "printers", "promotion", "patterns",
    "paragraph", "personals", "printable", "pregnancy", "portland", "parameter", "processor",
    "presents",
};
constexpr const char* kB_p_3[] = {
    "performance", "production", "protection", "particular", "population", "properties",
    "processing", "publication", "photography", "phentermine", "programming", "procedures",
    "publishing", "permission", "partnership", "provisions", "principles", "parameters",
    "philosophy", "prevention", "previously", "preparation", "playstation", "percentage",
    "participate", "proceedings", "psychology",
};
constexpr const char* kB_p_4[] = {
    "professional", "publications", "particularly", "presentation", "pennsylvania",
    "professionals", "participants", "philadelphia", "participation", "prescription",
    };
constexpr const char* kB_q_0[] = {
    "quote", "quick", "quite", "queen", "query",
};
constexpr const char* kB_q_1[] = {
    "quality", "quotes", "quickly", "quarter",
};
constexpr const char* kB_q_2[] = {
    "questions", "question", "quantity", "qualified",
};
constexpr const char* kB_r_0[] = {
    "read", "real", "right", "rate", "reply", "room", "rates", "road", "range", "radio", "rules",
    "rock", "risk", "river", "role", "rooms", "ready", "round", "rated", "rule", "ring", "rest",
    "race", "rape", "rent", "royal", "root", "rose", "rich", "rank", "reach", "route", "rural",
    "roll", "rare", "rise", "rings", "refer", "ratio", "rain", "ride", "runs", "rear",
};
constexpr const char* kB_r_1[] = {
    "rights", "review", "reviews", "report", "results", "related", "rating", "return", "really",
    "recent", "result", "release", "request", "reports", "region", "record", "records", "reading",
    "receive", "rather", "running", "robert", "rental", "returns", "reason", "ratings", "regular",
    "rentals", "retail", "require", "richard", "reader", "remote", "remove", "repair", "respect",
    "russian", "resort", "random", "replies", "reduce", "reasons", "racing", "reserve", "recipes",
    "readers", "russia", "revenue", "reality", "remain", "reduced", "removed", "regions",
    "removal", "revised", "relief", "recipe", "remains", "raised", "respond", "reflect",
    "reform", "replace", "reached",
};
constexpr const char* kB_r_2[] = {
    "research", "reserved", "resources", "register", "required", "reference", "resource",
    "received", "response", "remember", "regional", "releases", "recently", "relations",
    "republic", "reported", "released", "regarding", "requires", "relevant", "ringtones",
    "recommend", "religion", "reporting", "recovery", "requests", "religious", "returned",
    "residents", "reviewed", "reduction", "referred", "recording", "relative", "revision",
    "represent", "recorded", "receiving", "requested", "responses", "relating", "relation",
    };
constexpr const char* kB_r_3[] = {
    "registered", "responsible", "restaurants", "resolution", "recommended", "restaurant",
    "references", "respective", "regulations", "residential", "replacement", "recreation",
    "regulation", "reasonable", "requirement", "retirement", "recognition",
};
constexpr const char* kB_r_4[] = {
    "requirements", "registration", "responsibility", "relationship", "recommendations",
    "relationships", "representative", "reservations", "representatives",
};
constexpr const char* kB_s_0[] = {
    "site", "some", "state", "such", "said", "store", "send", "show", "sign", "south", "same",
    "size", "since", "shop", "small", "sites", "shall", "still", "save", "sale", "stock", "sales",
    "start", "study", "staff", "side", "story", "sell", "star", "space", "share", "self", "sure",
    "short", "says", "style", "sound", "sort", "step", "sony", "shows", "speed", "stuff", "shoes",
    "stay", "seen", "stop", "soon", "score", "sent", "shown", "super", "song", "smith", "safe",
    "sport", "ship", "stars", "sexy", "ships", "seems", "skin", "sense", "stage", "spain", "sets",
    "steel", "songs", "scale", "stand", "suite", "skip", "sheet", "seven", "sold", "stone", "steve",
    "shot", "scott", "shirt", "santa", "soft", "saint", "steps", "shops", "solid", "seem", "serve",
    "smart", "sorry", "snow", "soul", "stats", "sweet", "signs", "speak", "spam", "spent", "sleep",
    "scene", "seat", "slow", "spot", "spend", "specs", "sexo", "shape", "salt", "sharp", "seek",
    "soil", "sizes", "setup", "scope", "suck", "sugar", "stick", "slide", "storm",
};
constexpr const char* kB_s_1[] = {
    "search", "service", "should", "system", "support", "school", "states", "subject", "special",
    "section", "sports", "systems", "source", "science", "select", "series", "second", "server",
    "street", "student", "stores", "social", "single", "status", "seller", "similar", "schools",
    "stories", "society", "safety", "studies", "several", "submit", "simple", "storage",
    "summary", "started", "screen", "season", "someone", "sunday", "silver", "supply", "skills",
    "sellers", "sample", "summer", "spring", "survey", "sources", "secure", "simply", "station",
    "strong", "success", "senior", "session", "string", "studio", "surface", "sector", "showing",
    "spanish", "setting", "switch", "square", "selling", "species", "surgery", "servers",
    "seconds", "stream", "signed", "serious", "samsung", "sorted", "saying", "spirit", "suggest",
    "sitemap", "shirts", "seattle", "senate", "sponsor", "signal", "sexual", "stated", "savings",
    "script", "served", "speech", "shared", "sounds", "speaker", "secret", "springs", "sharing",
    "shemale", "serving", "samples", "singles", "static", "soccer", "scheme", "seeking",
    "shares", "smoking", "suites", "serial", "seeing", "sydney", "stress", "stephen", "sister",
    "smaller", "sweden", "spread", "symbol", "styles", "starts", "scores", "safari", "showed",
    "supreme",
};
constexpr const char* kB_s_2[] = {
    "services", "software", "shipping", "security", "students", "shopping", "september",
    "standard", "something", "specific", "solutions", "statement", "subscribe", "standards",
    "supplies", "sponsored", "selection", "solution", "saturday", "starting", "structure",
    "schedule", "selected", "searches", "strategy", "southern", "submitted", "subjects",
    "specified", "sometimes", "secretary", "situation", "sciences", "satellite", "settings",
    "sections", "supported", "separate", "sequence", "supplied", "straight", "scotland",
    "strategic", "slightly", "speakers", "supports", "secondary", "strength", "singapore",
    "standing", "specials", "signature", "stations", "suggested", "suppliers", "searching",
    "sporting", "speaking", "sponsors", "supplier", "specialty",
};
constexpr const char* kB_s_3[] = {
    "statistics", "significant", "successful", "scientific", "strategies", "statements",
    "suggestions", "structures", "supporting", "specialist", "securities", "switzerland",
    };
constexpr const char* kB_s_4[] = {
    "specifications", "subscription", "specifically",
};
constexpr const char* kB_t_0[] = {
    "that", "this", "time", "they", "their", "there", "these", "than", "them", "then", "terms",
    "type", "those", "take", "today", "three", "total", "think", "text", "times", "title", "tools",
    "teen", "team", "table", "test", "topic", "texas", "term", "track", "trade", "tell", "talk",
    "thing", "true", "third", "tips", "tech", "town", "toys", "taken", "turn", "types", "tour",
    "teens", "took", "tool", "thank", "tree", "thus", "takes", "told", "trial", "trust", "trip",
    "tests", "task", "tours", "tags", "theme", "touch", "tits", "truth", "teams", "tried", "taxes",
    "truck", "train", "tape", "toll", "trees", "tony", "trail",
};
constexpr const char* kB_t_1[] = {
    "through", "travel", "thread", "things", "tickets", "topics", "though", "thanks", "thought",
    "taking", "tuesday", "thomas", "trying", "traffic", "testing", "target", "theory", "teacher",
    "titles", "trading", "therapy", "towards", "talking", "tables", "turned", "theatre",
    "tourism", "toronto", "theater", "toward", "ticket", "turkey", "taylor", "tennis", "trends",
    "transit", "trouble", "totally", "tracks", "treated", "tested", "threads",
};
constexpr const char* kB_t_2[] = {
    "training", "technical", "together", "treatment", "thursday", "telephone", "therefore",
    "transfer", "teaching", "teachers", "transport", "thinking", "thousands", "thoughts",
    "tennessee", "trademark", "trackback", "tracking", "thailand", "template",
};
constexpr const char* kB_t_3[] = {
    "technology", "trademarks", "television", "throughout", "traditional", "themselves",
    "temperature", "techniques", "tripadvisor", "translation",
};
constexpr const char* kB_t_4[] = {
    "technologies", "transportation", "transmission", "transactions",
};
constexpr const char* kB_u_0[] = {
    "used", "user", "under", "using", "users", "until", "upon", "unit", "union", "units", "uses",
    "upper", "urban", "utah", "usage", "unix",
};
constexpr const char* kB_u_1[] = {
    "united", "updated", "update", "usually", "unique", "useful", "unless", "updates", "unknown",
    "upgrade", "utility",
};
constexpr const char* kB_u_2[] = {
    "username", "universal", "ultimate", "utilities", "unlimited", "upcoming",
};
constexpr const char* kB_u_3[] = {
    "university", "understand",
};
constexpr const char* kB_u_4[] = {
    "understanding",
};
constexpr const char* kB_v_0[] = {
    "view", "video", "very", "visit", "value", "views", "voice", "vote", "valid", "vegas", "virus",
    "void", "vice", "votes", "visa",
};
constexpr const char* kB_v_1[] = {
    "version", "videos", "various", "volume", "values", "valley", "vehicle", "virtual", "visual",
    "variety", "vision", "village", "viewed", "vintage", "vendor", "viewing", "voyeur", "viagra",
    "virgin",
};
constexpr const char* kB_v_2[] = {
    "virginia", "vacation", "visitors", "vehicles", "variable", "violence", "victoria",
    "versions", "variables", "volunteer",
};
constexpr const char* kB_v_3[] = {
    "verzeichnis",
};
constexpr const char* kB_w_0[] = {
    "with", "will", "what", "which", "when", "would", "were", "world", "work", "well", "where",
    "want", "women", "while", "water", "white", "west", "week", "write", "word", "works", "watch",
    "words", "wide", "whole", "wish", "weeks", "woman", "went", "wall", "wine", "ways", "wrote",
    "wood", "wrong", "worth", "wife", "whose", "wind", "waste", "wild", "walk", "wait", "wants",
    "wire", "wear", "wales", "whom", "wars", "wheel", "width", "wave", "warm",
};
constexpr const char* kB_w_1[] = {
    "within", "website", "without", "windows", "working", "welcome", "whether", "weather",
    "window", "written", "weight", "writing", "western", "wanted", "wedding", "william",
    "warning", "winter", "workers", "watches", "weekly", "worked", "weekend", "winning",
    "waiting", "writer", "wilson", "walking", "weblog", "wonder",
};
constexpr const char* kB_w_2[] = {
    "wireless", "wednesday", "worldwide", "websites", "williams", "wholesale", "workshop",
    "warranty", "wisconsin", "whatever", "wonderful", "webmaster", "wildlife",
};
constexpr const char* kB_w_3[] = {
    "washington",
};
constexpr const char* kB_x_0[] = {
    "xbox",
};
constexpr const char* kB_y_0[] = {
    "your", "year", "years", "york", "yahoo", "young", "youth", "yeah",
};
constexpr const char* kB_y_1[] = {
    "yellow",
};
constexpr const char* kB_y_2[] = {
    "yourself", "yesterday",
};
constexpr const char* kB_z_0[] = {
    "zone", "zoom", "zero",
};
constexpr const char* kB_z_1[] = {
    "zealand",
};

constexpr Bucket kBuckets[] = {
    {'a', 0, kB_a_0, 49},
    {'a', 1, kB_a_1, 83},
    {'a', 2, kB_a_2, 55},
    {'a', 3, kB_a_3, 26},
    {'a', 4, kB_a_4, 12},
    {'b', 0, kB_b_0, 68},
    {'b', 1, kB_b_1, 49},
    {'b', 2, kB_b_2, 18},
    {'b', 3, kB_b_3, 3},
    {'c', 0, kB_c_0, 73},
    {'c', 1, kB_c_1, 104},
    {'c', 2, kB_c_2, 81},
    {'c', 3, kB_c_3, 40},
    {'c', 4, kB_c_4, 13},
    {'d', 0, kB_d_0, 47},
    {'d', 1, kB_d_1, 49},
    {'d', 2, kB_d_2, 39},
    {'d', 3, kB_d_3, 20},
    {'d', 4, kB_d_4, 2},
    {'e', 0, kB_e_0, 31},
    {'e', 1, kB_e_1, 50},
    {'e', 2, kB_e_2, 42},
    {'e', 3, kB_e_3, 21},
    {'e', 4, kB_e_4, 3},
    {'f', 0, kB_f_0, 69},
    {'f', 1, kB_f_1, 59},
    {'f', 2, kB_f_2, 23},
    {'f', 3, kB_f_3, 4},
    {'g', 0, kB_g_0, 38},
    {'g', 1, kB_g_1, 26},
    {'g', 2, kB_g_2, 10},
    {'g', 3, kB_g_3, 4},
    {'h', 0, kB_h_0, 44},
    {'h', 1, kB_h_1, 31},
    {'h', 2, kB_h_2, 13},
    {'h', 3, kB_h_3, 2},
    {'i', 0, kB_i_0, 23},
    {'i', 1, kB_i_1, 25},
    {'i', 2, kB_i_2, 31},
    {'i', 3, kB_i_3, 23},
    {'i', 4, kB_i_4, 10},
    {'j', 0, kB_j_0, 18},
    {'j', 1, kB_j_1, 12},
    {'j', 2, kB_j_2, 1},
    {'j', 3, kB_j_3, 1},
    {'k', 0, kB_k_0, 17},
    {'k', 1, kB_k_1, 6},
    {'k', 2, kB_k_2, 3},
    {'l', 0, kB_l_0, 59},
    {'l', 1, kB_l_1, 45},
    {'l', 2, kB_l_2, 14},
    {'l', 3, kB_l_3, 4},
    {'m', 0, kB_m_0, 60},
    {'m', 1, kB_m_1, 62},
    {'m', 2, kB_m_2, 32},
    {'m', 3, kB_m_3, 9},
    {'m', 4, kB_m_4, 5},
    {'n', 0, kB_n_0, 23},
    {'n', 1, kB_n_1, 20},
    {'n', 2, kB_n_2, 9},
    {'n', 3, kB_n_3, 5},
    {'n', 4, kB_n_4, 1},
    {'o', 0, kB_o_0, 17},
    {'o', 1, kB_o_1, 30},
    {'o', 2, kB_o_2, 18},
    {'o', 3, kB_o_3, 4},
    {'o', 4, kB_o_4, 4},
    {'p', 0, kB_p_0, 61},
    {'p', 1, kB_p_1, 82},
    {'p', 2, kB_p_2, 78},
    {'p', 3, kB_p_3, 27},
    {'p', 4, kB_p_4, 10},
    {'q', 0, kB_q_0, 5},
    {'q', 1, kB_q_1, 4},
    {'q', 2, kB_q_2, 4},
    {'r', 0, kB_r_0, 43},
    {'r', 1, kB_r_1, 64},
    {'r', 2, kB_r_2, 42},
    {'r', 3, kB_r_3, 17},
    {'r', 4, kB_r_4, 9},
    {'s', 0, kB_s_0, 119},
    {'s', 1, kB_s_1, 124},
    {'s', 2, kB_s_2, 61},
    {'s', 3, kB_s_3, 12},
    {'s', 4, kB_s_4, 3},
    {'t', 0, kB_t_0, 73},
    {'t', 1, kB_t_1, 42},
    {'t', 2, kB_t_2, 20},
    {'t', 3, kB_t_3, 10},
    {'t', 4, kB_t_4, 4},
    {'u', 0, kB_u_0, 16},
    {'u', 1, kB_u_1, 11},
    {'u', 2, kB_u_2, 6},
    {'u', 3, kB_u_3, 2},
    {'u', 4, kB_u_4, 1},
    {'v', 0, kB_v_0, 15},
    {'v', 1, kB_v_1, 19},
    {'v', 2, kB_v_2, 10},
    {'v', 3, kB_v_3, 1},
    {'w', 0, kB_w_0, 53},
    {'w', 1, kB_w_1, 30},
    {'w', 2, kB_w_2, 13},
    {'w', 3, kB_w_3, 1},
    {'x', 0, kB_x_0, 1},
    {'y', 0, kB_y_0, 8},
    {'y', 1, kB_y_1, 1},
    {'y', 2, kB_y_2, 2},
    {'z', 0, kB_z_0, 3},
    {'z', 1, kB_z_1, 1},
};

} // namespace

std::span<const Bucket> english_word_buckets() {
    return {kBuckets, sizeof(kBuckets) / sizeof(kBuckets[0])};
}

} // namespace crux::media
